#theme: jekyll-theme-minimal
remote_theme: "just-the-docs/just-the-docs"

title: 💻Nicholas's Digital CV
description: A day in the DA-40 Aircraft.

#color_scheme: dark (dark mode)

logo: /images/happy2.jpg

allouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: Live Updates
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
      
    
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
